<?php
return [
    'home',
    'accessDenied',

    'masters.category.index',
    'masters.category.create',
    'masters.category.edit',
    'masters.category.show',
    'masters.category.delete',
    'masters.category.sync',
    'masters.category.approve', 

    'masters.subcategory.index',
    'masters.subcategory.create',
    'masters.subcategory.edit',
    'masters.subcategory.show',
    'masters.subcategory.delete',
    'masters.subcategory.sync',
    'masters.subcategory.approve', 

    'masters.department.index',
    'masters.department.create',
    'masters.department.edit',
    'masters.department.show',
    'masters.department.delete',
    'masters.department.sync',
    'masters.department.approve', 

    'masters.unit.index',
    'masters.unit.create',
    'masters.unit.edit',
    'masters.unit.show',
    'masters.unit.delete',
    'masters.unit.sync',
    'masters.unit.approve', 

    'masters.template.index',
    'masters.template.create',
    'masters.template.edit',
    'masters.template.show',
    'masters.template.delete',
    'masters.template.sync',
    'masters.template.approve', 
    
    'masters.template.version.index', 
    'masters.template.version.show', 
    'masters.template.version.edit', 
    'masters.template.version.edit.approve', 

    'masters.document.index',
    'masters.document.create',
    'masters.document.edit',
    'masters.document.show',
    'masters.document.delete',
    'masters.document.download',
    'masters.document.sync',
    'masters.document.approve', 
    'masters.document.workflow.index', 
    'masters.document.workflow.approve', 

    'masters.zone.index',
    'masters.zone.create',
    'masters.zone.edit',
    'masters.zone.show',
    'masters.zone.delete',
    'masters.zone.sync',
    'masters.zone.approve', 

    'masters.cluster.index',
    'masters.cluster.create',
    'masters.cluster.edit',
    'masters.cluster.show',
    'masters.cluster.delete',
    'masters.cluster.sync',
    'masters.cluster.approve',

    'masters.location.index',
    'masters.location.create',
    'masters.location.edit',
    'masters.location.show',
    'masters.location.delete',
    'masters.location.sync',
    'masters.location.approve',

    'masters.instrument.index',
    'masters.instrument.create',
    'masters.instrument.edit',
    'masters.instrument.show',
    'masters.instrument.delete',
    'masters.instrument.sync',
    'masters.instrument.approve',

    'clients.lab.index',
    'clients.lab.create',
    'clients.lab.edit',
    'clients.lab.show',
    'clients.lab.delete',

    'clients.lab.location.index',
    'clients.lab.location.create',
    'clients.lab.location.edit',
    'clients.lab.location.show',
    'clients.lab.location.delete',

    'clients.lab.clause.index',
    'clients.lab.clause.edit',
    'clients.lab.clause.show',
    'clients.lab.clause.delete',

    'clients.lab.assignments.index',
    'clients.lab.assignments.show',

    'settings.rolesPermission.index',
    'settings.rolesPermission.create',
    'settings.rolesPermission.edit',
    'settings.rolesPermission.delete',

    'settings.user.index',
    'settings.user.create',  
    'settings.user.edit',  
    'settings.user.show',  
    'settings.user.delete',

    'settings.standard.index',
    'settings.standard.create',
    'settings.standard.edit',
    'settings.standard.show',
    'settings.standard.delete',
    'settings.standard.clause.index',
    'settings.standard.clause.create',
    'settings.standard.clause.edit',
    'settings.standard.clause.show',
    'settings.standard.clause.delete',
    'settings.standard.action.index',
    'settings.standard.action.approve',
    
    'settings.account.index',
    'settings.account.edit',

    'settings.menu.index',
    'settings.menu.rename',
];
